[tool.black]
line-length = 79

[tool.isort]
multi_line_output = 3
combine_as_imports = true
include_trailing_comma = false

force_grid_wrap = 2

use_parentheses = true
ensure_newline_before_comments = true
line_length = 79
indent = 4
atomic = true
case_sensitive = false
balanced_wrapping = false
